<a href="https://colab.research.google.com/github/GerardoMunoz/Curso_Python/blob/main/Algoritmo_Matriz_Escalon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Habilidades utilizadas:
* Habilidades para el trabajo en equipo, ya que deben paralelizar las tareas a realizar y luego deben integrar los trabajos individuales.
* Habilidades para gestión de proyectos, ya que se ilustran metodologías ágiles.
* Habilidades analíticas, ya que se debe generalizar el procedimiento realizado mediante un algoritmo.
* Habilidades para realizar código en Python
* Habilidades para probar código
* Habilidades para medir y comparar el desempeño en tiempo y recursos utilizados
* Habilidades para poder comprender un programa ya desarrollado
* Habilidades para consultar documentación y autoaprendizaje

# Algoritmo de Eliminación de Gauss

## Pasos para obtener la forma escalón
 [Nakos, Sec. 1.2]
1. Vaya a la columna extrema izquierda que no sea de ceros.
2. Si el primer renglón tiene un cero en la columna del paso (1), intercámbielo con uno que tenga un elemento no cero en la misma columna.
3. Obtenga ceros debajo del elemento delantero, sumando múltiplos adecuados del renglón superior a los renglones debajo de él.
4. Cubra el renglón superior y repita el mismo proceso comenzando por el paso (1) aplicado a la sub-matriz restante. Repita este proceso con el resto de los renglones.


## Paso para obtener la forma escalón reducida
5. Comenzando con el último renglón no cero, avance hacia arriba: para cada renglón obtenga un 1 delantero e introduzca ceros arriba de él, sumando múltiplos adecuados a los renglones correspondientes.

## Ejemplo
En el siguiente enlace se presenta un ejemplo.
https://colab.research.google.com/github/GerardoMunoz/PresentacionesAlgebraLineal/blob/main/AL06_OpElem.ipynb#scrollTo=kBa6oyX1FRLa

## Ejercicio:

Implemente en Python el algoritmo de Eliminación de Gauss utilizando los principios de las metodologías Agiles.

## Desarrollo

La metodología a implementar consiste en proponer al menos una función para cada uno de lo pasos propuestos y luego determinar cuales pasos son los más representativos aplicable al mayor número de matrices.

### Funciones propuestas


A continuación vamos a desarrollar el algoritmo con un programa en Python utilizando la librería `numpy`. Para lo cual se esbozan las siguientes funciones, las cuales se pueden asociar a los pasos del algoritmo.





In [2]:
# 1. Vaya a la columna extrema izquierda que no sea de ceros.

def columna_izquierda_no_ceros(M):
  columna = 0
  ... #Código en construcción
  return columna


In [3]:
# 2. Si el primer renglón tiene un cero en la columna del paso (1),
# intercámbielo con uno que tenga un elemento no cero en la misma
# columna.

def intercambia_si_es_cero(M,col):
  ... #Código en construcción
  return M

In [4]:
# 3. Obtenga ceros debajo del elemento delantero, sumando múltiplos adecuados del
# renglón superior a los renglones debajo de él.

def elimina_ceros_debajo(M,col):
  ... #Código en construcción
  return M

In [5]:
# 4. Cubra el renglón superior y repita el mismo proceso
# comenzando por el paso (1) aplicado a la sub-matriz restante.
# Repita este proceso con el resto de los renglones.

def repite_elimina_abajo_a_submatrices(M,col):
  ... #Código en construcción
  return M

In [6]:
# 5. Comenzando con el último renglón no cero,
# avance hacia arriba: para cada renglón obtenga un 1
# delantero e introduzca ceros arriba de él,
# sumando múltiplos adecuados a los renglones correspondientes

def uno_delantero_y_ceros_arriba(M,delantero):
  ... #Código en construcción
  return M

In [7]:
def repite_elimina_arriba_a_renglones(M,col):
  ... #Código en construcción
  return M

### Priorizar los pasos

Los pasos requeridos por todas las matrices son el 3 y el 4, los cuales se realizarán de primeras para obtener la matriz escalón de algunas matrices (las matrices invertibles).

Luego, se desarrollará el paso 1, de esta forma podemos obtener matrices escalón de matrices no invertibles.

El paso 2 es muy esporádico. Sin embargo, al implementarlo quedan cubiertos todos los casos para obtener la matriz escalón.

Finalmente se realiza el paso 5 que permite obtener matrices escalón reducidas a partir de matrices escalón.

# Generalización para obtener ceros bajo el pivote.

Comenzamos seleccionando algunos pasos fáciles de generalizar. El paso seleccionado es el paso 3 donde  el patrón observado es

```
M[i,:] = M[i,:] + M[j,:]*M[i,k]/M[j,k]
M[i+1,:] = M[i+1,:] + M[j,:]*M[i+1,k]/M[j,k]
repite hasta el último renglón
```

Para repetir se puede utilizar un `while` *mientras* el renglón no sea el último. También, se puede repetir con un `for` *para* los renglones que faltan, ya que desde el comienzo se pueden calcular.  En este caso utilizaremos el `for`.  

In [8]:
def elimina_ceros_debajo(M,ren,col):
  #El pivote debe ser diferente de cero
  m,n=M.shape
  for i in range(ren+1,m):
    M[i,:] = M[i,:] - M[ren,:]*M[i,col]/M[ren,col]
  return M


Ahora probamos el código


In [9]:
M0=np.array([
    [ 2.0,  3],
    [ 5,  7],
    [11, 13],
])

M1=elimina_ceros_debajo(M0,0,0)
M1

array([[ 2. ,  3. ],
       [ 0. , -0.5],
       [ 0. , -3.5]])

In [10]:
M2=elimina_ceros_debajo(M1,1,1)
M2

array([[ 2. ,  3. ],
       [ 0. , -0.5],
       [ 0. ,  0. ]])

# Obtener ceros para todas las columnas

Ahora voy a realizar el paso 4, el cual puede omitir los pasos 1 y 2 para algunas matrices. En particular con matrices invertibles.



In [11]:
def repite_elimina_abajo_a_submatrices(M):
  m,n = M.shape
  for j in range(m):
    M = elimina_ceros_debajo(M,j,j)
  return M

M0=np.array([
    [ 2.0,  3, -1],
    [ 5,  7,  -2],
    [11, 13, -3],
])

M2=repite_elimina_abajo_a_submatrices(M0)
M2

array([[ 2. ,  3. , -1. ],
       [ 0. , -0.5,  0.5],
       [ 0. ,  0. , -1. ]])

# Evitar columnas de ceros

Para generalizar a matrices no invertibles necesitamos detectar si debajo del pivote hay ceros.


In [12]:
def columna_izquierda_no_ceros (M,ren,col):
  m,n=M.shape
  for j in range(col,n):
    if M[ren:,j].any():
      break
  ######## En que caso se ejecuta el  `else` en un for ##############
  else:
    j = n
  ##################################################################
  return j

M=np.array([
      [ 2. ,  3. , -1. ],
      [ 0. , 0. ,  0.5],
      [ 0. ,  0. , -1. ]
    ])

columna_izquierda_no_ceros(M,0,0)

0

In [13]:
columna_izquierda_no_ceros(M,1,0)

2



Ahora generalizamos la función `repite_elimina_abajo_a_submatrices` para algunas matrices no invertibles

In [14]:
def repite_elimina_abajo(M):
  m,n = M.shape
  col=0
  for ren in range(m):
    col=columna_izquierda_no_ceros(M,ren,col)
    ######### Explique para que se requieren   ############################
    ######### las siguientes dos instrucciones ############################
    if col==n:
      break
    #######################################################################
    M = elimina_ceros_debajo(M,ren,col)
  return M

M0=np.array([
    [ 2.0,  4, -1,  4, -1],
    [ 5,  20,  -2.5,  10,  -2.5],
    [11, 22, -5.5, 2, -5.5],
    [11, 22, -5.5, 22, -5.5],
    [11, 22, -5.5, 22, -5.5],
])

M2 = repite_elimina_abajo_a_submatrices(M0)
M2

<ipython-input-8-f8f9e6129907>:5: RuntimeWarning: invalid value encountered in divide
  M[i,:] = M[i,:] - M[ren,:]*M[i,col]/M[ren,col]


array([[  2.,   4.,  -1.,   4.,  -1.],
       [  0.,  10.,   0.,   0.,   0.],
       [  0.,   0.,   0., -20.,   0.],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan]])

### Cuando el pivote es cero

Ahora sí se implementa el  paso 2. Para identificar y corregir si el pivote es cero.

In [15]:
def intercambia_si_es_cero(M,ren,col):
  m,n=M.shape
  if 0==M[ren,col]:
    for i in range(ren,m):
      if 0!=M[i,col]:
        M[[i,ren]]=M[[ren,i]]
        break
  return M

M0=np.array([[  0,   4.,  -1.,   4.,  -1.],
       [  0.,  10.,   0.,   0.,   0.],
       [  2,   0.,   0., -20.,   0.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]])

intercambia_si_es_cero(M0,0,0)

array([[  2.,   0.,   0., -20.,   0.],
       [  0.,  10.,   0.,   0.,   0.],
       [  0.,   4.,  -1.,   4.,  -1.],
       [  0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.]])

A continuación se integra la rutina al resto del programa.

In [24]:
def repite_elimina_abajo(M):
  m,n = M.shape
  col=0
  for ren in range(m):
    col=columna_izquierda_no_ceros(M,ren,col)
    if col==n:
      break
    intercambia_si_es_cero(M,ren,col)
    M = elimina_ceros_debajo(M,ren,col)
  return M

M0=np.array([
    [ 0.0,  0, -1,  4, -0],
    [ 5,  10,  -2.5,  10,  -2.5],
    [11, 22, -5.5, 22, -5.5],
    [11, 22, -5.5, 22, -5.5],
    [11, 22, -5.5, 22, -5],
    [11, 22, -5.5, 22, -5],

])

M2=repite_elimina_abajo(M0)
M2


array([[ 5. , 10. , -2.5, 10. , -2.5],
       [ 0. ,  0. , -1. ,  4. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0.5],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ],
       [ 0. ,  0. ,  0. ,  0. ,  0. ]])

## Ejercicio:

### Obtener ceros arriba de los pivotes

Continue desarrollando el paso faltante, puede desarrollar el código para obtener ceros arriba del pivote o modificar el anterior código para obtener ceros arriba del pivote cuando se obtienen abajo del pivote (Gauss-Jordan).

### Verificación final

Proponga un conjunto de matrices con características que prueben los diferentes casos y realice un programa que pueda probar el código realizado. Corrija los errores si se presentan.

## Librería array
La librería array permite ahorrar espacio con arreglos de números. La cual se documenta en el siguiente enlace https://docs.python.org/es/3/library/array.html

## Ejercicio
Implemente en array las funciones que se utilizaron de numpy en la eliminación de Gauss. Ya que array es de una dimensión puede implementar una matriz como un vector, donde el primer elemento almacena el número de columnas.



# Ejercicio
Calcule la complejidad algorítmica del anterior algorítmo en cuanto tiempo y recursos utilizados en términos del número de renglones y columnas