# Lista de listas

In [32]:
A_lista=[[1,2,2],[4,5,6]]
A_lista

[[1, 2, 2], [4, 5, 6]]

In [33]:
type(A_lista)

list

In [34]:
A_lista[0]

[1, 2, 2]

In [35]:
A_lista[0][0]

1

# Arreglos de `numpy`

In [36]:
import numpy as np
A = np.array(A_lista)
A

array([[1, 2, 2],
       [4, 5, 6]])

In [37]:
type(A)

numpy.ndarray

In [38]:
A[0,0]

1

In [39]:
type(A[0,0])

numpy.int32

In [40]:
A[0,0]=2**30
A

array([[1073741824,          2,          2],
       [         4,          5,          6]])

In [41]:
A[0,0]=2**31
A

OverflowError: Python int too large to convert to C long

In [42]:
A[0,0]=2**31-1
A

array([[2147483647,          2,          2],
       [         4,          5,          6]])

In [43]:
A[0,0] += 1
A

C:\ProgramData\Miniconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in long_scalars
  """Entry point for launching an IPython kernel.


array([[-2147483648,           2,           2],
       [          4,           5,           6]])

Recomiendo ver "How do I catch a numpy warning like it's an exception (not just for testing)?" en Stackoverflow.

In [45]:
np.array([1])/0

C:\ProgramData\Miniconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([inf])

In [13]:
B_lista=[2**x for x in range(5)]
B_lista

[1, 2, 4, 8, 16]

In [14]:
B=np.array(B_lista)
B

array([ 1,  2,  4,  8, 16])

In [15]:
B[0]

1

In [16]:
type(B[0])

numpy.int32

In [17]:
C_lista=[2**x for x in range(0,40,5)]
C_lista

[1, 32, 1024, 32768, 1048576, 33554432, 1073741824, 34359738368]

In [18]:
C=np.array(C_lista)
C

array([          1,          32,        1024,       32768,     1048576,
          33554432,  1073741824, 34359738368], dtype=int64)

In [19]:
C[0]

1

In [20]:
type(C[0])

numpy.int64

In [21]:
D_lista=[2**x for x in range(0,80,10)]
D_lista

[1,
 1024,
 1048576,
 1073741824,
 1099511627776,
 1125899906842624,
 1152921504606846976,
 1180591620717411303424]

In [22]:
D=np.array(D_lista)
D

array([1, 1024, 1048576, 1073741824, 1099511627776, 1125899906842624,
       1152921504606846976, 1180591620717411303424], dtype=object)

In [23]:
D[0]

1

In [24]:
type(D[0])

int

In [25]:
E_lista=[10**x for x in range(20)]
E_lista

[1,
 10,
 100,
 1000,
 10000,
 100000,
 1000000,
 10000000,
 100000000,
 1000000000,
 10000000000,
 100000000000,
 1000000000000,
 10000000000000,
 100000000000000,
 1000000000000000,
 10000000000000000,
 100000000000000000,
 1000000000000000000,
 10000000000000000000]

In [26]:
E=np.array(E_lista)
E

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09, 1.e+10, 1.e+11, 1.e+12, 1.e+13, 1.e+14, 1.e+15,
       1.e+16, 1.e+17, 1.e+18, 1.e+19])

In [27]:
E[0]

1.0

In [28]:
type(E[0])

numpy.float64

In [46]:
E[-1]

1e+19

In [48]:
E[-1]+=1
E

array([1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07,
       1.e+08, 1.e+09, 1.e+10, 1.e+11, 1.e+12, 1.e+13, 1.e+14, 1.e+15,
       1.e+16, 1.e+17, 1.e+18, 1.e+19])

 Cuando `dtype=object` no se pueden realizar algunas operaciones matriciales como la inversión.
 Es posible cambiar el tipo de dato usando `astype`

In [52]:
Id_lista=[[2, 0],[0, 5]]
F=np.array(Id_lista)
F

array([[2, 0],
       [0, 5]])

In [53]:
type(F[0,0])

numpy.int32

In [54]:
np.linalg.inv(F)

array([[0.5, 0. ],
       [0. , 0.2]])

In [58]:
G=F.astype(np.float64)
G

array([[2., 0.],
       [0., 5.]])

In [59]:
np.linalg.inv(F)

array([[0.5, 0. ],
       [0. , 0.2]])

In [58]:
G=F.astype(np.float64)
G

array([[2., 0.],
       [0., 5.]])

In [59]:
np.linalg.inv(F)

array([[0.5, 0. ],
       [0. , 0.2]])

In [67]:
H=np.array([[2**80, 0], [0, 2**80]])//2**80
H

array([[1, 0],
       [0, 1]], dtype=object)

In [68]:
type(H[0,0])

int

In [69]:
np.linalg.inv(H)

TypeError: No loop matching the specified signature and casting was found for ufunc inv